name: test-global
# Workflow qui construit les tests, construit image docker, qui push sur docker hub, le tout en  pull request
on:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du repo
        uses: actions/checkout@v2
      - name: Setup sur node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: 'Install Dependencies'
        run: 'npm ci'
      - name: Initialisation des tests
        run: npm test #car environnement NODE JS
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du repo
        uses: actions/checkout@v2
      - name: Setup sur node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: 'Install Dependencies'
        run: 'npm ci'
      - name: Installation de QEMU Docker #Installation de l'émulateur et virtualiseur de docker
        uses: docker/setup-qemu-action@v1
      - name: Installation de BuildX Docker #plugin CLI qui rajoute(=extends) des commandes à Docker
        uses: docker/setup-buildx-action@v1
      - name: Connexion à docker
        uses: docker/login-action@v1
        with:
         #Insertion de la variable dans github https://github.com/{user}/weather/settings/secrets/actions
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build et push de l'image docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rzahar/weather:latest